spring:
  application:
    name: rocketmq-service
  profiles:
    active: dev

server:
  port: 5300


eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/


feign:
  hystrix:
    enabled: true
logging:
  level:
    com:
      cloud:
        address:
          mapper: debug

